name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }} 

jobs:
  terraform:

    name: Terraform CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 5.70.0
          
      - name: Terraform Format Check
        run: terraform fmt -check
        
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=plan.out

      # Uncomment the following step if you want to apply changes on main branch only
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve plan.out

      - name: Upload Plan Output
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan
          path: plan.out
